server:
  port: 8082

spring:
  application:
    name: mscv-group
  datasource:
    url: jdbc:postgresql://localhost:5432/groups_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: mik3123

    jpa:
      hibernate:
        ddl-auto: create
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      show-sql: true
  config:
    import: optional:configserver:http://localhost:8888

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka