runtime: nodejs20 
env: standard

handlers:
 
  - url: /(.*\.[\w]{2,4})$
    static_files: dist/\1
    upload: dist/(.*) 
  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html 

automatic_scaling:
  min_instances: 1
  max_instances: 2
  target_cpu_utilization: 0.8